# Generated by Django 3.2.8 on 2021-10-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='colab',
        ),
    ]
