# Generated by Django 3.2.8 on 2021-10-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211013_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('special_status', 'Can read all projects')]},
        ),
    ]
